filebeat.inputs:
  - type: log
    paths:
      - /var/logs/*.log
    multiline:
      pattern: ^\d{4}
      negate: true
      match: after
    tail_files: true
    fields:
      app_id: devops-dtp
      pattern_type: java
      env: {{elk_env}}  # 应用部署环境，方便多环境共用elk时区分（根据实际情况也可以考虑去掉这个字段）

output.logstash:
  hosts: ["{{elk_logstash}}"] # logstash地址
